### ISSUE TITLE
to_colormap(:Viridis, n) always returns 20 colors

### ISSUE THREAD

**Issue by Benoit9** [JuliaPlots/AbstractPlotting.jl#1]
I see it's hardcoded in conversions.jl
A missing call to resample ?

**Comment by anthony-wang** [comment]
Nice catch, I actually just fixed this 2 days ago ;)

https://github.com/JuliaPlots/AbstractPlotting.jl/commit/b4654bf4a0fbc762edf28f1fcdb6f01295dc8341

I also added some tests in `Makie.jl` for it: https://github.com/JuliaPlots/Makie.jl/commit/56f6e94f3b7d80ff798e703f817a642daadb12c5 and https://github.com/JuliaPlots/Makie.jl/commit/ebd40423459230fa08c8d2c1085c126154128609
