### ISSUE TITLE
UndefVarError: removehandler_callbacks not defined

### ISSUE THREAD

**Issue by goretkin** [JuliaPlots/AbstractPlotting.jl#109]
At https://github.com/JuliaPlots/AbstractPlotting.jl/blob/e2f48d328b3341da367bd41611df31627bb19f6d/src/interaction/nodes.jl#L53

Seems to come from a missing definition. It can probably be removed altogether.
https://github.com/JuliaGizmos/Observables.jl/blob/77e984fc72765ab1b30486809300255c1361f715/src/Observables.jl#L8

This never gets triggered, except when I was trying to use `@enter` from `Debugger.jl`

**Comment by asinghvi17** [comment]
Fixed by #111
