### ISSUE TITLE
Bounding box or camera error in AbstractPlotting#master?

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/AbstractPlotting.jl#110]
MWE:
```julia
using Makie
arc(0, 1, 0, π)
```
yields
<img width="481" alt="Screen Shot 2019-04-04 at 10 28 39  18300PM" src="https://user-images.githubusercontent.com/32143268/55600327-82213200-5729-11e9-84af-4f6308838667.png">
Looks like a camera issue since `update_cam!` fixes it...

EDIT: This is happening on any plot on both master and 0.9.6...suspecting it might be something on my system?

**Comment by asinghvi17** [comment]
perhaps because `origin` wants to be an int instead of an array or point?

**Comment by asinghvi17** [comment]
Perhaps the camera is set incorrectly?  Only thing I could think of...

**Comment by asinghvi17** [comment]
Yep, just a weird bug on my system.  Reinstalling fixes it.

**Comment by SimonDanisch** [comment]
If this happens again, try an explicit `display(scene)` ... this can happen if there is an error in the display code, which the display system sometimes doesn't propagate -.-
