### ISSUE TITLE
customize some attributes in type recipes

### ISSUE THREAD

**Issue by piever** [JuliaPlots/AbstractPlotting.jl#14]
Allow  `convert_arguments` to also specify some default attributes, as in:

```julia
function convert_arguments(::Type{AbstractPlot}, x::MyType)
    return (new_args...), Theme(...)
end
```

**Comment by piever** [comment]
This may actually be more of a documentation issue. It may be that what I'm trying to do should be done by overloading:

```julia
function plot!(scene::SceneLike, P::Type{<:AbstractPlot}, attr::Attributes, x::MyType)
    plot!(scene, P, newattr, newargs...)
end
```

So maybe we don't need any change, but just to document this more. Especially one can use `pop!` on the `Attributes` to take out only those that are specific to the plot. Btw, can this `Attributes` object be modified in the pipeline, or I should make copies?

**Comment by SimonDanisch** [comment]
Yeah this is sort of possible, but there are a couple of issues with it ;)
Maybe we can just solve those, instead of further misusing convert_arguments^^

**Comment by piever** [comment]
This signature seems quite nice, as I can decide what to do with the plot type, what to do with the attributes and how to convert the arguments, so maybe overloading it could be the default implementation of type recipes?

What are the issues? So far it has worked reasonably well for me...

**Comment by SimonDanisch** [comment]
Mainly interaction with nodes... you can't just make `Node(::MyType)` work as easily :(

**Comment by piever** [comment]
I was also a bit surprised as to why here I don't need to `lift` over the argument, but only over the attribute. That definitely felt strange. But this feels like the most useful signature to fix: one has all the relevant information. It'd be great if these interaction issue could be fixed.

**Comment by asinghvi17** [comment]
Is this possible now?
