### ISSUE TITLE
NoConversion trait?

### ISSUE THREAD

**Issue by tk3369** [JuliaPlots/AbstractPlotting.jl#146]
I'm looking at the `ConversionTrait` code and found the use of [nothing trait](https://github.com/JuliaPlots/AbstractPlotting.jl/blob/b6ef7a99eb0e77267ce30d76b4bcb08da3ebade8/src/conversions.jl#L40-42).

```
conversion_trait(x) = nothing
# nothing trait - don't convert
convert_arguments(::Nothing, args...) = args
```

Wouldn't it be cleaner with a new `NoConversion` trait? 

```
struct NoConversion <: ConversionTrait end

conversion_trait(::Type) = NoConversion()
convert_arguments(::NoConversion, args...) = args
```

**Comment by SimonDanisch** [comment]
I guess? ;) Do you want to make a PR?
