### ISSUE TITLE
Aspect ratio ignored

### ISSUE THREAD

**Issue by yakir12** [JuliaPlots/AbstractPlotting.jl#169]
When specifying `scale_plot = false` the resulting plot does not have an aspect ratio of 1. 

I activated a new environment in an empty directory:
```julia
(v1.1) pkg> activate .
(tmp) pkg> add AbstractPlotting#master GLMakie#master Makie#master
```
and plotted a unit circle:
```julia
using Makie
t = range(0, 2π, length = 100)
p = lines(cos.(t), sin.(t), scale_plot = false)
save("a.png", p)
```
which resulted in this ellipse:
![a](https://user-images.githubusercontent.com/3281957/61619238-bedc4f00-ac6e-11e9-84b6-df5a4c1d9540.png)

**Comment by asinghvi17** [comment]
It looks like #166 fixes this.  You could give that a try by `]add AbstractPlotting#sd-improvements`.
![lol](https://user-images.githubusercontent.com/32143268/61621201-17701400-ac90-11e9-865b-2cf0e6fd0e31.png)

**Comment by asinghvi17** [comment]
Just fun to note, but there's a shorter solution that gets you this plot:
```julia
lines(Circle(Point2f0(0), 1f0)
```
although the axis limits are different
![lol](https://user-images.githubusercontent.com/32143268/61622010-99147180-ac91-11e9-9ab9-3531340467e4.png)
Something to investigate @SimonDanisch?

**Comment by yakir12** [comment]
I tried with the `sd-improvements` branch and the resulting circle is still an ellipse (regardless if I plot with a geometry primitive or by calculating the coordinates). And when I tried to save it I got this error:
```julia
save("a.pdf", sc)
ERROR: MethodError: no method matching format2mime(::Type{FileIO.DataFormat{:UNKNOWN}})
Closest candidates are:
  format2mime(::Type{FileIO.DataFormat{:PNG}}) at /home/yakir/.julia/packages/AbstractPlotting/pgMBD/src/display.jl:165
  format2mime(::Type{FileIO.DataFormat{:SVG}}) at /home/yakir/.julia/packages/AbstractPlotting/pgMBD/src/display.jl:166
  format2mime(::Type{FileIO.DataFormat{:JPEG}}) at /home/yakir/.julia/packages/AbstractPlotting/pgMBD/src/display.jl:167
```
So in short, that branch might not be ready?

**Comment by asinghvi17** [comment]
You can't save as PDF, only PNG.

**Comment by asinghvi17** [comment]
Hmm...does it display correctly but save wrong?

**Comment by SimonDanisch** [comment]
>Hmm...does it display correctly but save wrong?

Since I can't reproduce it and never run into this before, is that maybe it? Can you share the exact steps to reproduce it?

**Comment by yakir12** [comment]
Since this is no longer an issue -- I for one cannot reproduce it -- I'm closing this. Thanks!
