### ISSUE TITLE
Specify level values in contour

### ISSUE THREAD

**Issue by grero** [JuliaPlots/AbstractPlotting.jl#208]
Hi,
 I was wondering if there is a way to specify the values of the levels in contour, rather than just the number of levels? My scenario is that I would like to compare matrices of decoding performance for slightly different decoders. I find that contours work better than heatmaps for visualising each matrix, but to compare them, I'd want the contour levels to be drawn at the same values for each matrix. Thanks!

**Comment by mkborregaard** [comment]
Yes, sure. Have you tried just passing a Vector to `levels`?
