### ISSUE TITLE
Specify the type of zoom_step in the `zoom!` func. 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/AbstractPlotting.jl#210]
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/27697b4045c62a5c7a1c868403949dfb84d752b6/src/camera/camera3d.jl#L211-L215

WHat's the type of `zoom_step`? Should that be in the docstring?

**Comment by asinghvi17** [comment]
Just a number I think
