### ISSUE TITLE
Type inference regression from Julia 1.3 to 1.4-DEV

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/AbstractPlotting.jl#223]
```julia
using AbstractPlotting
Scene()
```
works on 1.3, but enters an endless loop of type inference on 1.4 (commit JuliaLang/julia@71c4d9bb1938cb2a7916e64a6d705725026c9285 and JuliaLang/julia@0a277811c8).

is_derived_type at ./compiler/typelimits.jl:71
is_derived_type at ./compiler/typelimits.jl:58
is_derived_type at ./compiler/typelimits.jl:71
is_derived_type at ./compiler/typelimits.jl:58
is_derived_type at ./compiler/typelimits.jl:71
is_derived_type at ./compiler/typelimits.jl:58
is_derived_type at ./compiler/typelimits.jl:71
is_derived_type at ./compiler/typelimits.jl:58
is_derived_type at ./compiler/typelimits.jl:71
is_derived_type at ./compiler/typelimits.jl:58
is_derived_type at ./compiler/typelimits.jl:71
is_derived_type at ./compiler/typelimits.jl:58
is_derived_type at ./compiler/typelimits.jl:71
is_derived_type at ./compiler/typelimits.jl:58
is_derived_type at ./compiler/typelimits.jl:71
is_derived_type at ./compiler/typelimits.jl:58

...

**Comment by SimonDanisch** [comment]
I think you should open this issue at the Julia repository!
There is nothing to do here, if Julia stops working ;)

**Comment by asinghvi17** [comment]
True, just putting it here to keep it in case I forget to raise the issue there :)
