### ISSUE TITLE
`Base.convert(Node{T}, x)` yields `Node{Any}`

### ISSUE THREAD

**Issue by CarpeNecopinum** [JuliaPlots/AbstractPlotting.jl#250]
Due to https://github.com/JuliaPlots/AbstractPlotting.jl/blob/420fa25071fd9ee65a2fd65eb1355324aa044076/src/types.jl#L289

conversion to a concrete node type yields a result of `Node{Any}` rather than type parameter passed.

```
typeof(convert(Node{Bool}, false))
> Observables.Observable{Any}
```

In particular, this breaks structs with Node fields with a slightly confusing error message:

```
struct Foo x::Node{Bool} end
Foo(false)
> ERROR: TypeError: in new, expected Observables.Observable{Bool}, got Observables.Observable{Any}
Stacktrace:
 [1] Foo(::Bool) at ./none:1
 [2] top-level scope at none:0
```

**Comment by asinghvi17** [comment]
It looks like that signature can be safely deleted?  Will run the tests, see if anything comes up

**Comment by CarpeNecopinum** [comment]
Potentially yes, I didn't look into it in much more detail. For now (due to plenty of other work to do) I "fixed" it on my end by defining my own `convert(Node{T},...)`. At least it didn't break anything in the portion of Makie that I actively use, though.

Judging by @SimonDanisch 's reaction on slack, I was expecting this to be a more complicated endeavor:
> per default, we need to assume Node{Any}  to make e.g. this work:
> scene = scatter(rand(4), color = :red)
> scene[end].color = RGB(1, 0,0) 

and

> Oh yeah, that's true :smile: completely overlooked, that I actually put the Base.convert definition.. > yeah that's pretty bad even
> I guess I couldn't hunt down all locations, where conversion was happening, so I was lazy and just overloaded convert :sweat_smile:

**Comment by SimonDanisch** [comment]
Yeah, maybe I removed the parts that rely on this by now - but, the convert method needs to be moved out of AbstractPlotting completely: https://github.com/JuliaPlots/AbstractPlotting.jl/pull/255
