### ISSUE TITLE
Excessive export?

### ISSUE THREAD

**Issue by piever** [JuliaPlots/AbstractPlotting.jl#26]
```julia
julia> using Distributions

julia> using AbstractPlotting
WARNING: using AbstractPlotting.Text in module Main conflicts with an existing identifier.
WARNING: using AbstractPlotting.scale! in module Main conflicts with an existing identifier.
```

`AbstractPlotting.Text` conflicts with `Text` from Base: I think it's really strange to export something that exists in Base with a different meaning. `AbstractPlotting.scale!` conflicts with `Distributions.scale!`. The signatures don't seem to overlap though, but it's strange to take a dependency on Distributions just to overload the same function.

**Comment by asinghvi17** [comment]
I think this is no longer an issue?  @piever please confirm...I haven't seen it recently

**Comment by SimonDanisch** [comment]
It should be... I think though, that Base actually shouldn't export Text... It's super random type with almost no usability to anyone using Julia :D

**Comment by asinghvi17** [comment]
Okay, closing this then.  Please reopen if this specific issue is seen, though I doubt it will be.
