### ISSUE TITLE
float32type(::DataType) should be caught

### ISSUE THREAD

**Issue by rapus95** [JuliaPlots/AbstractPlotting.jl#262]
I'm still investigating how I got there, but currently it results in an infinite recursion. Thus I'd say this should be caught and handled somehow.

EDIT: I got there because my array contained missings and the type was `Union{Missing, Float64}`. Is there any way to render missings in a heatmap with a customcolor outside of the color range for valid values?

**Comment by SimonDanisch** [comment]
You can replace it with NaN, which should come out as transparent....

**Comment by SimonDanisch** [comment]
Also, this fixes the actual issue: https://github.com/JuliaPlots/AbstractPlotting.jl/commit/4acab1fe1ea6647c426e0bceb7a0d2deb785b1c7
