### ISSUE TITLE
RGBA volumes

### ISSUE THREAD

**Issue by vilim** [JuliaPlots/AbstractPlotting.jl#269]
Hello! How does one plot 3D volumes with RGBA values? 
Putting a 3D array of RGBAf0 values in as the argument to `volume!` gives the following error:
```MethodError: no method matching GLMakie.GLVisualize.VolumePrerender()```

Also, is additive blending possible? Absorption is I guess subtractive blending, suitable for displays with white background?

**Comment by SimonDanisch** [comment]
This seems fixed:
```julia
volume(rand(RGBAf0, 3, 3, 3); algorithm = :absorptionrgba)
```

>Also, is additive blending possible?

That would be quite easy to add here: https://github.com/JuliaPlots/GLMakie.jl/blob/master/src/GLVisualize/assets/shader/volume.frag#L182

I currently have more pressing issues to work on though :(
