### ISSUE TITLE
camera zooming with orthographic projection type

### ISSUE THREAD

**Issue by jaakkor2** [JuliaPlots/AbstractPlotting.jl#276]
In this example the zooming does not work out-of-plane, but moves the image in-plane.  I would expect to see similar zooming as in the `Perspective` option.
```julia
using Makie
using GLMakie
scene = wireframe(GLMakie.loadasset("cat.obj"))
cam = cameracontrols(scene)
cam.projectiontype[] = Makie.AbstractPlotting.Orthographic # not zooming
#cam.projectiontype[] = Makie.AbstractPlotting.Perspective # works as expected
update_cam!(scene, cam)
```

Edit: AbstractPlotting 0.9.17, GLMakie 0.0.13

**Comment by jaakkor2** [comment]
Problematic lines are at
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/8274bf4346a1ca43e1b1e880c9f2a37e9e89c61b/src/camera/camera3d.jl#L236-L238
if I comment those out, zooming in orthographic projection works as I would expect.

Those lines came from https://github.com/JuliaPlots/AbstractPlotting.jl/commit/08b63d29dd965e63b3cb128e8649be2bb5743d35, but the intent is unclear for me. Why would one shift `cam.lookat[]` when zooming? And why this is happening in orthographic projection, but not in perspective projection.

**Comment by SimonDanisch** [comment]
Well, there are two ways to zoom, one is to change the field of view, the other to move the camera closer... To me it seemed like it makes sense, if moving the camera closer, to also move the look at... But maybe that's not true...
I just tried to set shift_lookat [here](https://github.com/JuliaPlots/AbstractPlotting.jl/blob/8274bf4346a1ca43e1b1e880c9f2a37e9e89c61b/src/camera/camera3d.jl#L82) to false and the camera doesn't seem to feel worse^^
So i'd be open to change that ;)

**Comment by SimonDanisch** [comment]
Feel free to open a PR to merge that change ;)
