### ISSUE TITLE
Failed to precompile AbstractPlotting on win32 platform

### ISSUE THREAD

**Issue by ashindin** [JuliaPlots/AbstractPlotting.jl#28]
On clean Julia 1.0.0 (and 1.0.1) at win32 platform (at 2 different machines). After adding AbstractPlotting package (`]add AbstractPlotting` or `]add AbstractPlotting#master`) and after `using AbstractPlotting` I got following:

[ Info: Precompiling AbstractPlotting [537997a7-5e4e-5d89-9595-2241ea00577e]

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1575cc21 -- #68 at C:\Users\ashindin\.julia\packages\AbstractPlotting\4EywS\src\scenes.jl:201 [inlined]
ntuple at .\tuple.jl:133
in expression starting at C:\Users\ashindin\.julia\packages\AbstractPlotting\4EywS\src\scenes.jl:234
#68 at C:\Users\ashindin\.julia\packages\AbstractPlotting\4EywS\src\scenes.jl:201 [inlined]
ntuple at .\tuple.jl:133
_primary_resolution at C:\Users\ashindin\.julia\packages\AbstractPlotting\4EywS\src\scenes.jl:200 [inlined]
primary_resolution at C:\Users\ashindin\.julia\packages\AbstractPlotting\4EywS\src\scenes.jl:215
reasonable_resolution at C:\Users\ashindin\.julia\packages\AbstractPlotting\4EywS\src\scenes.jl:222
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1841
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1831
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2184
do_call at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:324
eval_value at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:430
eval_stmt_value at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:678
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:795
unknown function (ip: FFFFFFFE)
unknown function (ip: 1B3D5C8F)
unknown function (ip: 00000001)
jl_interpret_toplevel_thunk at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:804
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:813
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win32/build/src\ast.c:838
jl_load at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:847 [inlined]
jl_load_ at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:854
_applyn at /home/Administrator/buildbot/worker/package_win32/build/src/flisp\flisp.c:682
include at .\sysimg.jl:29 [inlined]
include at C:\Users\ashindin\.julia\packages\AbstractPlotting\4EywS\src\AbstractPlotting.jl:1
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1841
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2184
do_call at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:324
eval_value at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:430
eval_stmt_value at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:678
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:795
unknown function (ip: FFFFFFFE)
unknown function (ip: 1B3BE37F)
unknown function (ip: FFFFFFFF)
jl_interpret_toplevel_thunk at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:804
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:813
jl_eval_module_expr at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:233
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:651
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win32/build/src\ast.c:838
jl_load at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:847 [inlined]
jl_load_ at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:854
include at .\boot.jl:317 [inlined]
include_relative at .\loading.jl:1041
include at .\sysimg.jl:29
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1841
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2184
do_call at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:324
eval_value at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:430
eval_stmt_value at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:678
eval_body at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:613
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:795
unknown function (ip: FFFFFFFE)
unknown function (ip: 0E778E7F)
unknown function (ip: 00000002)
jl_interpret_toplevel_thunk at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:804
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:813
jl_toplevel_eval at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:822
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win32/build/src\builtins.c:622
eval at .\boot.jl:319 [inlined]
eval at .\client.jl:389
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1841
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2184
top-level scope at .\none:3
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1841
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1831
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:807
jl_toplevel_eval at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:822
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win32/build/src\builtins.c:622
eval at .\boot.jl:319
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1841
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2184
macro expansion at .\logging.jl:317 [inlined]
exec_options at .\client.jl:219
_start at .\client.jl:421
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1841
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2184
jl_apply at /home/Administrator/buildbot/worker/package_win32/build/src\julia.h:1537 [inlined]
true_main at /home/Administrator/buildbot/worker/package_win32/build/ui\repl.c:112
wmain at /home/Administrator/buildbot/worker/package_win32/build/ui\repl.c:233
__tmainCRTStartup at /usr/src/debug/mingw64-i686-runtime-5.0.3-1/crt\crtexe.c:329
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
PssNtCaptureSnapshot at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
PssNtCaptureSnapshot at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 11867069 (Pool: 11866327; Big: 742); GC: 49
ERROR: Failed to precompile AbstractPlotting [537997a7-5e4e-5d89-9595-2241ea00577e] to C:\Users\ashindin\.julia\compiled\v1.0\AbstractPlotting\6fydZ.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] macro expansion at .\logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1187
 [4] _require(::Base.PkgId) at .\logging.jl:311
 [5] require(::Base.PkgId) at .\loading.jl:855
 [6] require(::Module, ::Symbol) at .\logging.jl:311

**Comment by asinghvi17** [comment]
Is this still an issue?  Please feel free to reopen if so...
