### ISSUE TITLE
License for Fonts

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaPlots/AbstractPlotting.jl#30]
@Evizero pointed out, that AbstractPlotting ships some fonts without proper license!

@aviks was so kind to hunt down the licenses:

* DejaVu License: https://dejavu-fonts.github.io/License.html
* Noto license: https://github.com/googlei18n/noto-fonts/blob/master/LICENSE
* Black Chancery _seems_ to be public domain, but I can’t find a definitive source
* Hack is MIT on top of Bitstream: https://github.com/source-foundry/Hack/blob/master/LICENSE.md
* Fira: https://github.com/mozilla/Fira/blob/master/LICENSE

I'm not 100% sure how to attribute the licenses, and need to leave this for today, hence this issue to not forget about it!

**Comment by asinghvi17** [comment]
Could we ship a LICENSES.md in `assets/fonts`?

**Comment by SimonDanisch** [comment]
Maybe that's the way to go ;)

**Comment by asinghvi17** [comment]
Cool, it's been added in my new-version branch
