### ISSUE TITLE
`volume(mat; isorange = any_value)` not working on mac

### ISSUE THREAD

**Issue by Malpaca** [JuliaPlots/AbstractPlotting.jl#302]
MWE:
```julia
r = range(-1,stop=1,length=5)
matr=[(x.^2 + y.^2 + z.^2) for x = r, y = r, z = r]
matr2 = matr .* (matr .> 1.4)
volume(matr2,algorithm=:iso, isovalue = 1.5, isorange=3)
```
This produced the following plot:
![with_range](https://user-images.githubusercontent.com/18019064/74174299-ae3af880-4c01-11ea-9292-5de5362acff5.png)

Removing the isorange argument produced the following plot:
![without_range](https://user-images.githubusercontent.com/18019064/74174307-b1ce7f80-4c01-11ea-9d2e-5f864096abd2.png)

**Comment by SimonDanisch** [comment]
Oh seems like a convert is missing... It works with `isorange=3f0`

**Comment by SimonDanisch** [comment]
Should be fixed!
