### ISSUE TITLE
Issue with tick setters and automatic limits

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/AbstractPlotting.jl#317]
They don't work, since the limits need to be materialized.  Not sure what's to be done here...

**Comment by SimonDanisch** [comment]
Can you give an example of what's happening?

**Comment by asinghvi17** [comment]
```julia
scene = Scene()
scene.limits[]
# AbstractPlotting.Automatic()
```

Then, when the `setlims!` function tries to get the current limits, it ends up getting `automatic` instead.
