### ISSUE TITLE
More flexible font selection

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaPlots/AbstractPlotting.jl#336]
Just posting that here to save it for VizCon. I have said before that I don't like the current way to specify fonts. It is hard to impossible to select the correct variant when you have a font with X different weights or other styles. I also don't like using freetype's attributes to select a font, because they can be hard to find out when trying to discriminate between special variants. How do you know quickly whether the font you want has weight 400, 500, 600, 700? Or what other special type attributes are? I think the easiest way is to do better fuzzy search on font names, because those you know when you want to choose a font. This way nobody has to worry about choosing the exact spelling of the post script name, or something annoying like that, they just have to kind of spell the font correctly.

For example, let's say I want to choose the font "SF Pro Display Semibold Italic".
This doesn't work:
```julia
ax = LAxis(scene, title = "A great scene",
        titlefont = "SF Pro Display Semibold Italic", titlesize = 40)

Warning: Could not find font SF Pro Display Semibold Italic, using Dejavu Sans
```
Even though the font exists. I can use "Times New Roman" even though there is no font with that exact name (only "Times New Roman Bold", "Times New Roman Regular", etc...). So it essentially chooses one by chance now, and with less common fonts you will not get the one you want. Especially if it's a variant like "Avenir Next Condensed Ultra Light" or something like that. `FreeTypeAbstraction.findfont` uses only family name, bold and italic. How are you supposed to find this font with those parameters?

What does work is this:
```julia
scene, layout = layoutscene()

font = FreeTypeAbstraction.try_load(raw"C:\Users\krumbiegel\AppData\Local\Microsoft\Windows\Fonts\SFProDisplay-SemiboldItalic.ttf")

ax = LAxis(scene, title = "A great scene",
    titlefont = [font], titlesize = 40)
layout[1, 1] = ax

scene
```

But this is obviously horrible in terms of the user experience. So I think we should just make it really easy to choose a font by the **full** name, and not rely on FreeType for that.

**Comment by SimonDanisch** [comment]
I tried integrating: https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/pull/26, but couldn't get Fontconfig to run on my pc..
Maybe we could just have an additional, optional API a la:
```julia
using FontConfig
LAxis(scene, title = "A great scene",
        titlefont = findfont("SF Pro Display Semibold Italic"), titlesize = 40)
```
Btw, why did you delete: https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/pull/24 ?
Was that improving things, or did you close it because it wasn't working?

**Comment by jkrumbiegel** [comment]
I think it didn't work anymore when you tried it, did it? I think the `findfont` option is unnecessary when we just make the internal matching function less buggy. Are there good reasons against going completely by font name with some sort of fuzzy search like I implemented in that closed PR?

One reason why one would maybe want the FontConfig way is that you could replace `findfont("Arial", bold = true, italic = true)` with `findfont("Verdana", bold = true, italic = true)` and would get the "same style" with a different font. In practice that just doesn't make sense as most fonts have more variants and then you just have the problems I described above.

Other plotting packages also don't get this right (matplotlib also makes it hard to choose the exactly right font variant via its supposedly "intelligent" attribute matching). I think two ways should work easily:
- fuzzy font name matching to specify variants correctly of fonts in standard folders
- path to a font file, for cases where a font file is for example distributed with some code and just accessed locally. this should also be as easy as doing `font = path_to_font`

**Comment by jkrumbiegel** [comment]
there could just be an `@info` telling you which font was actually selected by fuzzy matching

**Comment by SimonDanisch** [comment]
>Are there good reasons against going completely by font name with some sort of fuzzy search like I implemented in that closed PR?

No, only that you closed it, and there were reasons against the Fontconfig PR (Fontconfig being buggy on at least my PC) ;)

**Comment by jkrumbiegel** [comment]
well at the time I think you were in favor of implementing FontConfig correctly, but now I still think the other solution is better. I'll revive it, maybe tomorrow ;)

**Comment by SimonDanisch** [comment]
>well at the time I think you were in favor of implementing FontConfig correctly

I still am, but these ancient C libraries keep tricking me :D 

> I'll revive it, maybe tomorrow ;)

Awesome :)

**Comment by jkrumbiegel** [comment]
done
