### ISSUE TITLE
`convert_attribute` is not applied to primitives

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/AbstractPlotting.jl#377]
For some reason, whenever I run 
```julia
scatter(rand(10); marker = 'a', font = "Helvetica") # random font
```
in the backend, `primitive.font` is a String instead of an FTFont.  This also happens for colors (Symbols and Ints are not converted to RGB(A)).

**Comment by SimonDanisch** [comment]
This is expected behaviour...Conversions are lazy, so the backend needs/can decide when to do the conversion! 
call `convert_attribute(x, key"scatter", key"font")` to do the right conversion
