### ISSUE TITLE
Layout is clumsy in combination with the plot! recipe approach

### ISSUE THREAD

**Issue by piever** [JuliaPlots/AbstractPlotting.jl#39]
We quickly mentioned this on slack but I think it deserves its own issue. The standard way to create layouts seems to be:

```jullia
scene3 = vbox(scene1, scene2)
```

which makes it quite clumsy to create recipes that have a layout, where one should instead modify a scene in place.

Possible solutions:

- Restore something like `grid!` that would change the layout in place
- Add to the scene type a method `scene.layout` that would be used to determine the layout on rendering (it's the technique used in [Interact](https://juliagizmos.github.io/Interact.jl/latest/custom_widgets.html#Widgets.@layout!))

**Comment by jkrumbiegel** [comment]
think I can close this given makielayout
