### ISSUE TITLE
[FR] Add "alpha" keyword to `to_colormap`.

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/AbstractPlotting.jl#399]
Will make `AbstractPlotting.to_colormap(:viridis, N)` very convenient!

**Comment by Datseris** [comment]
My version:
```

function colors_from_map(cmap, α, N)
    cs = [RGBAf0(c.r, c.g, c.b, α) for c in AbstractPlotting.to_colormap(cmap, N)]
end
```

**Comment by asinghvi17** [comment]
Would `colormap = (:viridis, alpha)` be a good API for this?

**Comment by Datseris** [comment]
No, I don't think so. What a colormap is is very clear in users head from years using colormaps.

Besides, your version does not simplify at least my function.

**Comment by asinghvi17** [comment]
Your invocation would be changed to `to_colormap((:viridis, 0.8), N)`, which IMO is a reasonable one, especially since we support e.g. `color = (:red, 0.8)` for colors.
