### ISSUE TITLE
Add support for categorical values on x axis

### ISSUE THREAD

**Issue by piever** [JuliaPlots/AbstractPlotting.jl#49]
At the moment `barplot(["a", "b", "c"], rand(3))` errors, but ideally it should convert the strings to `1:3`, and let a "hint" to the scene that the preferred ticks values are `["a", "b", "c"]` at location `[1, 2, 3]`.

**Comment by mkborregaard** [comment]
Would it make sense to convert String x inputs to CategoricalArray and then have a convert_arguments for that?

**Comment by piever** [comment]
That's probably a good idea, to just have one "default" type for categorical data. Especially because then we'd be in a better position to support custom ordering.

**Comment by asinghvi17** [comment]
I think this is supported now?
