### ISSUE TITLE
Enable https for the site

### ISSUE THREAD

**Issue by musm** [JuliaPlots/AbstractPlotting.jl#707]
Please open your issue at https://github.com/JuliaPlots/Makie.jl/issues/new unless you've been explicitly pointed here by a Makie developer.

**Comment by SimonDanisch** [comment]
What site?

**Comment by musm** [comment]
Main site: http://makie.juliaplots.org/stable/

**Comment by musm** [comment]
Try going there and enabling it:
![image](https://user-images.githubusercontent.com/4319522/116427337-f0a22280-a811-11eb-9853-d90506451157.png)

**Comment by SimonDanisch** [comment]
I get: 
![image](https://user-images.githubusercontent.com/1010467/116428394-27456080-a845-11eb-9951-0a80190b709d.png)
Not sure what needs to be changed in:
https://github.com/JuliaPlots/Makie.jl/blob/master/CNAME

**Comment by musm** [comment]
Do you have the custom domain typed out?

**Comment by musm** [comment]
I would remove the `CNAME` from https://github.com/JuliaPlots/Makie.jl/blob/master/CNAME 
and work on fixing it here since that's where the documentation is built.

**Comment by musm** [comment]
If you don't have the time to fix this I'll be happy to help.

**Comment by SimonDanisch** [comment]
Oh, didn't realize, that the docs get pushed to https://github.com/JuliaPlots/MakieDocumentation these days..
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/docs/make.jl#L408
There I have the option to enforce https... Lets see how that goes ;)

**Comment by musm** [comment]
Great that works now!

**Comment by musm** [comment]
Yeah it's a bit strange that the docs are pushed to  https://github.com/JuliaPlots/MakieDocumentation 

Especially since the documentation version is synced to `AbstractPlotting`:

On the website https://makie.juliaplots.org/stable/
![image](https://user-images.githubusercontent.com/4319522/116429906-555e7c80-a814-11eb-924a-27d68f57f9df.png)

Which has nothing to do with the `Makie` version number

**Comment by musm** [comment]
It would probably be easier to host the docs here, and would likely fix the CI issue that required the doc PR pushed to be from an Admin account.

**Comment by SimonDanisch** [comment]
Yeah, the Makie version number is not relevant at all these days, since everything happens in AbstractPlotting.
We want to move the code from AbstractPlotting to Makie at some point, to clean this all up... But its a bit of work with renaming + keeping commit history
