### ISSUE TITLE
`button` should work for clicking anywhere in the box

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/AbstractPlotting.jl#75]
Hello,

I initialize a button like:
```julia
    statebutton = AbstractPlotting.button(Theme(raw = true, camera = campixel!), "latest state")
    on(statebutton[end][:clicks]) do c
        u0, col = laststate[]
        println("Latest state: ")
        println(u0)
        println("with color: $(col)")
    end
```

which looks like:

![image](https://user-images.githubusercontent.com/19669089/52169563-ca789f80-273a-11e9-8f91-afe3247a86e1.png)

In the image I have circled with blue places where I click the `button` but it does not trigger. In fact after trial and error I found that the button only triggers if you press exactly on the letters or exactly on the borders. It does not trigger when you press the white space in-between. I think this is unintuitive and also not the behavior one expects when using a "button". 

I mean, the buttons on my keyboard work even If I press the black space inbetwee then white lines that define the letters, right? ;)

**Comment by c42f** [comment]
I just encountered this, it's a bug.

The problem seems to be that there's no background rendered for buttons, so there's no object ID in those pixels to be picked when clicked upon. The glyphs each have a little box around them including the transparent and non-transparent parts of the glyph, which is why you can click on the white spaces inside a letter and still get the button to trigger.

**Comment by SimonDanisch** [comment]
@c42f I thought you were right, but I did actually render a transparent background, which, while not optimal, is enough to render out an id ;) It was instead a simple mess up when flattening the plots for checking the id!

**Comment by c42f** [comment]
Aha! So the background id wasn't being picked up? That makes sense.  (I didn't read the id code, but I *thought* I'd checked what was going on visually by fiddling with the shader.)

**Comment by SimonDanisch** [comment]
>So the background id wasn't being picked up?

No, it was! It just didn't find it in the supplied plots, since the background mesh was one level deeper ;)
