### ISSUE TITLE
AbstractObservable not defined

### ISSUE THREAD

**Issue by sebastianpech** [JuliaPlots/AbstractPlotting.jl#76]
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/0b75085cdc948b03bc85d17d9db587f872f9f4db/src/interaction/nodes.jl#L5

Observables does not export `AbstractObservable`. This should be changed to `Observables.AbstractObservable`

**Comment by SimonDanisch** [comment]
oh, thanks!

**Comment by SimonDanisch** [comment]
weird, pretty sure I tested this!
