### ISSUE TITLE
README DOCS/EXAMPLES

### ISSUE THREAD

**Issue by EricAlcaide** [JuliaPlots/AbstractPlotting.jl#93]
Would be useful to provide some examples or a link to a very basic documentation to encourage usage.

**Comment by mkborregaard** [comment]
Have you seen https://github.com/JuliaPlots/MakieGallery.jl ?

**Comment by SimonDanisch** [comment]
[Makie.jl](https://github.com/JuliaPlots/Makie.jl) is likely the package you're looking for!
Makie relies on AbstractPlotting to do its thing, but AbstractPlotting itself can't do any plotting!

**Comment by EricAlcaide** [comment]
Wow thank you both for the short and useful answer!
